version: 0.2

env:
  parameter-store:
    GITHUB_TOKEN: "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"

phases:
  install:
    commands:
      - ${CODEBUILD_SRC_DIR}/scripts/ci/install_packages.sh
  build:
    commands:
      - ${CODEBUILD_SRC_DIR}/scripts/ci/format.sh
      - ${CODEBUILD_SRC_DIR}/scripts/ci/validate.sh
      - ${CODEBUILD_SRC_DIR}/scripts/ci/lint_aws.sh
      - ${CODEBUILD_SRC_DIR}/scripts/ci/plan.sh
